Timing: add generated code jit timing feature
facebookexperimental/object-introspection pull request #180
Opened 2023-06-23 16:35 UTC by JakeHillion

## Summary

Adds a timing call at the beginning and end of the generated code functions and store the time taken in nanoseconds in the data segment. Currently this is output at `LOG(INFO)` level. IMO this belongs in RocksDB and `oid_out.json`, but it requires a bit of a format change so I'll leave it until it's necessary.

This required adding another `uintptr_t` typed element to the data segment prefix, to avoid the overhead of varint serialization and extra addition at the end (probe effect). It should be incredibly minimal as is, but as it's feature gated and off by default I haven't bothered measuring it. I added some names to pieces in these entry functions while I was in there, and also cleaned up a type in the typed data segment entry.

## Test plan
- CI
- `[]: make test: 100% tests passed, 0 tests failed out of 578`
- `["-fjit-timing"]: make test: 100% tests passed, 0 tests failed out of 578`
- `["-ftype-graph"]: make test: 94% tests passed, 33 tests failed out of 578`
- `["-ftype-graph", "-fjit-timing"]: make test: 94% tests passed, 33 tests failed out of 578`
- `["-ftyped-data-segment"]: make test: 86% tests passed, 80 tests failed out of 578`
- `["-ftyped-data-segment", "-fjit-timing"]: make test: 86% tests passed, 80 tests failed out of 578`
(that was hard work)

2023-06-26 12:59 UTC, ajor approved these changes
[cppreference](https://en.cppreference.com/w/cpp/chrono/high_resolution_clock) doesn't have a high opinion of `high_resolution_clock`:

> The high_resolution_clock is not implemented consistently across different standard library implementations, and its use should be avoided.
> ...
> Generally one should just use [std::chrono::steady_clock](https://en.cppreference.com/w/cpp/chrono/steady_clock) or [std::chrono::system_clock](https://en.cppreference.com/w/cpp/chrono/system_clock) directly instead of std::chrono::high_resolution_clock: use steady_clock for duration measurements, and system_clock for wall-clock time.

2023-06-26 14:03 UTC, ttreyer requested changes
It looks mostly good to me 🙂 
Could you change the bool flag to the actual feature set, as discussed, please.
Also take a look at the `data[3]` idea.

2023-06-26 14:03 UTC, ttreyer commented on oi/FuncGen.cpp
> +      writtenSize = 0;
Would it be simpler to always have `data[3]` dedicated for the timing info?
Set it to 0 when the feature is disabled, populate it otherwise.

2023-06-29 10:49 UTC, ajor approved these changes

2023-07-03 16:42 UTC, ttreyer approved these changes

2023-07-03 17:02 UTC, merged