Implement Container V2 for F14VectorMap
facebookexperimental/object-introspection pull request #338
Opened 2023-09-06 12:55 UTC by ttreyer

## Summary
Implement Container V2 for `folly::F14VectorMap`.

## Test plan
Tests in `folly_f14_vector_map.toml` cover this implementation, but we'll have to wait for the CI to confirm they pass.

2023-09-06 20:09 UTC, ttreyer commented
I'm not sure my additions to `oi/OITraceCode.cpp` are the right way to do this. I'd love some feedback on that particular part.

2023-09-07 12:14 UTC, ajor commented
> I'm not sure my additions to `oi/OITraceCode.cpp` are the right way to do this. I'd love some feedback on that particular part.

There are a few strange things I see going on in the old f14_vector_map.toml file:
- `numTemplateParams` is specified to be 2 and `replaceTemplateParamIndex` is not defined, which means the HeterogeneousAccessHash template parameter is not being stubbed out
- `allocatorIndex` is not specified, so the allocator parameter is not being removed

I'm not sure how this has been working previously, but without looking into and fixing those other problems, I think a better workaround for the HeterogeneousAccessHash issue would be to force CodeGen v1 to include the folly namespace with:
```
ns = ["namespace folly"]
```

All of these issues are for CodeGen v1 only, so I wouldn't spend much time investigating them as v1 will hopefully be going away entirely soon.

2023-09-07 14:12 UTC, ttreyer commented
I kept the "namespace folly" out for now and stubbed both parameters out. Both F14NodeMap and F14FastMap had proper values for `replaceTemplateParamIndex` and `allocatorIndex`, but only F14VectorMap was missing these. Since we don't need these template parameters to traverse the containers, I'm happy to go that way!

2023-09-07 14:38 UTC, ajor requested changes
I think the json_v2 results for these types are wrong: they're all showing sizes of 24 no matter how many elements are in the containers and don't match the v1 results.

2023-09-07 14:38 UTC, ajor commented on types/f14_node_map.toml
> +      .write(container.size());
These look like the right things to save, but `traversal_func` isn't including them.

Side note: is this `handler` used for anything now the new `traversal_func` method exists?

2023-09-07 15:13 UTC, ajor approved these changes
Fair enough, yeah let's merge then but not forget!

2023-09-07 16:47 UTC, merged