OID: Add "tree-builder" feature flag to control whether the data segment is processed
facebookexperimental/object-introspection pull request #412
Opened 2023-11-15 19:21 UTC by ajor

It defaults to enabled, so there is no change from the current behaviour.

It may be useful to disable tree builder when the data segment is very large and processing it would take too many resources on the host machine.

## Test plan
Manual testing:
- Confirmed that tree builder is run with "-ftree-builder"
- Confirmed that tree builder is not run with "-Ftree-builder"
- Confirmed that the "-B" dump data segment option works with the "tree-builder" feature enabled and disabled.

2023-11-15 19:43 UTC, tyroguru approved these changes

2023-11-15 23:00 UTC, JakeHillion requested changes
Could we add this as a field in `Oid::Config` instead of a feature? It could be added as a `mode` for a similar UX to features, though you can't undo turning a mode on yet. The reason for this is all the features so far directly affect code generation (I realise they are used elsewhere too) and therefore it's been a really clean way to affect the build hash. It would be nice to have the things which exclusively control the running of the debugger in a different set.

2023-11-16 10:55 UTC, tyroguru commented
> Could we add this as a field in `Oid::Config` instead of a feature? It could be added as a `mode` for a similar UX to features, though you can't undo turning a mode on yet. The reason for this is all the features so far directly affect code generation (I realise they are used elsewhere too) and therefore it's been a really clean way to affect the build hash. It would be nice to have the things which exclusively control the running of the debugger in a different set.

The ideal way to communicate this IMO is via a mechanism that is attached to a probe in the script - this has been talked about before. In that way the state travels with the probe specification. I had completely forgot that was use the features to control cache generation and obviously we don't want to trigger a rebuild for something that doesn't affect the generated BLOB.

2023-11-16 11:03 UTC, JakeHillion commented
> > Could we add this as a field in `Oid::Config` instead of a feature? It could be added as a `mode` for a similar UX to features, though you can't undo turning a mode on yet. The reason for this is all the features so far directly affect code generation (I realise they are used elsewhere too) and therefore it's been a really clean way to affect the build hash. It would be nice to have the things which exclusively control the running of the debugger in a different set.
> 
> The ideal way to communicate this IMO is via a mechanism that is attached to a probe in the script - this has been talked about before. In that way the state travels with the probe specification. I had completely forgot that was use the features to control cache generation and obviously we don't want to trigger a rebuild for something that doesn't affect the generated BLOB.

A command line flag that only affects the debugger and not the cache blob seems good. A change to the script would also be fine, but we'd have to be careful about caching too then - currently we'd be able to hash the entire script text/parsed script and get a decently useful thing for the hash. With pragmas that affect how the debugger runs and not codegen we'd have to be a lot more careful. Something to think about longer term.

2023-11-16 14:51 UTC, ajor commented
Updated to avoid using feature flags

2023-11-16 15:25 UTC, merged